// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressGif(arg1, arg2) {
  return window['go']['main']['App']['CompressGif'](arg1, arg2);
}

export function CompressImage(arg1, arg2) {
  return window['go']['main']['App']['CompressImage'](arg1, arg2);
}

export function CreateGifFromSequence(arg1, arg2) {
  return window['go']['main']['App']['CreateGifFromSequence'](arg1, arg2);
}

export function GetImageInfo(arg1) {
  return window['go']['main']['App']['GetImageInfo'](arg1);
}

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
