// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompressGif(arg1:string,arg2:main.GifCompressOptions):Promise<main.GifResult>;

export function CompressImage(arg1:string,arg2:main.CompressOptions):Promise<main.CompressResult>;

export function CreateGifFromSequence(arg1:Array<string>,arg2:main.GifOptions):Promise<main.GifResult>;

export function GetImageInfo(arg1:string):Promise<main.ImageInfo>;

export function GetSupportedFormats():Promise<Record<string, Array<string>>>;

export function SelectImages():Promise<Array<string>>;

export function SelectOutputDir():Promise<string>;
